#! /bin/bash

#update frome a server

#version   v0.1    2015/11/26  lr75106   基本功能 
#          v0.2    2015/12/3   lr75106   模块化函数
#          v0.3    2015/12/24  lr75106   优化重构


flag()
{
    f_flag=0
    fm_flag=0
    fi_flag=0
    s_flag=0
    sm_flag=0
    si_flag=0

}

sed_cfg()
{
    host=$(sed -n '1p' /opt/spice/config.ftp)
    name=$(sed -n '2p' /opt/spice/config.ftp)
    passwd=$(sed -n '3p' /opt/spice/config.ftp)
    server_path=$(sed -n '4p' /opt/spice/config.ftp)
    local_path=$(sed -n '5p' /opt/spice/config.ftp)
   # file_name=$(sed -n '6p' /opt/spice/config.ftp)
    up_name=$(sed -n '7p' /opt/spice/config.ftp)
    gz_name=$(sed -n '8p' /opt/spice/config.ftp)
    name_log=$(echo linkosky |sudo -S hdparm -I /dev/sda |grep 'Serial Number'|awk -F " " 'NR==1''{print $3}'
    )
}


check()
{
    if du $gz_name 2>/dev/null 
    then
        f_flag=1
        echo linkosky |sudo -S touch check.md5
        echo linkosky |sudo -S chmod 777 check.md5
        md5sum $gz_name > check.md5
        md5sum -c check.md5&&fm_flag=1
        echo linkosky |sudo -S rm check.md5
        tar zxf $gz_name
        file_name=$(sed -n '1p' updata.info)
    fi

    if du $up_name 2>/dev/null
    then
        s_flag=1
        echo linkosky |sudo -S touch check0.md5
        echo linkosky |sudo -S chmod 777 check0.md5
        md5sum $up_name > check0.md5
        md5sum -c check0.md5&&sm_flag=1
        echo linkosky |sudo -S rm check0.md5
    fi
}

install_updata()
{
    if [ $fm_flag -eq 1 ]
    then
        echo linkosky |sudo -S dpkg -i $file_name&&\
        fi_flag=1
    fi

    if [ $sm_flag -eq 1 ]
    then
        echo linkosky |sudo -S rm -rf mftp.x&&\
        echo linkosky |sudo -S mv $up_name mftp.x&&\
        echo linkosky |sudo -S chmod 755 mftp.x&&\
        si_flag=1
    fi
}


write_log()
{
    echo linkosky|sudo touch ${name_log}.log
    echo linkosky|sudo chmod 777 ${name_log}.log
    echo $file_name >>${name_log}.log
    echo ${name} >>${name_log}.log
    date "+%Y-%m-%d %H:%M:%S" >>${name_log}.log
    echo package detected >>${name_log}.log
    if [ $fm_flag -eq 1 ]
    then
        echo check_install_file ok! >>${name_log}.log
    else
        echo check_install_file fail>>${name_log}.log
    fi

    if [ $fi_flag -eq 1 ]
    then
        echo install_package ok! >>${name_log}.log
    else
        echo install_package fail>>${name_log}.log
    fi

    if [ $si_flag -eq 1 ]
    then
        echo updata_up_self ok! >>${name_log}.log
    else
        echo updata_up_self fail>>${name_log}.log
    fi
}


get_file()
{
    sed_cfg
    echo linkosky |sudo -S ftp -n<<!
    open $host
    user $name $passwd
    binary
    prompt
    get $gz_name
    get $up_name
    close
    bye
!
}

put_file()
{
    echo linkosky |sudo -s ftp -n<<!
    open $host
    user $name $passwd
    brinary
    prompt
    put ${name_log}.log
    close
    bye
!
    echo linkosky |sudo rm $file_name ${name_log}.log $gz_name updata.info 
}

get_file
flag
check
if [ $f_flag -eq 1 ]
then
    install_updata
    write_log
    put_file
else
    echo nothing to do
fi


